[package]
name = "excel_to_csv"
version = "0.1.0"
authors = ["Todd Roth <tjroth@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine="0.16.1"
